name: Go Tests

on:
  push:
    branches:
      - main
      - develop
      - features/automated-test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build server
        run: go build -o mini-alt main.go

      - name: Start server with -test
        env:
          SECRET_ENCRYPTION_KEY: 1234567890abcdef1234567890abcdef
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: ./mini-alt -test &

      - name: Wait for server
        run: |
          for i in {1..10}; do
            if nc -z localhost 9000; then
              echo "✅ Server is up!"
              exit 0
            fi
            echo "⏳ Waiting for server..."
            sleep 2
          done
          echo "❌ Server did not start in time" && exit 1

      - name: Run tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: go test -v ./test/...
